CREATE TABLE USER_CHAT (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE USER_MESSAGE (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    message TEXT NOT NULL,
    chat INTEGER,
    created_at DATETIME,

    FOREIGN KEY(chat) REFERENCES USER_CHAT(id)
);

CREATE TABLE BOT_MESSAGE (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    message TEXT NOT NULL,
    chat INTEGER,
    created_at DATETIME,

    FOREIGN KEY(chat) REFERENCES USER_CHAT(id)
);
